=== cesario74/PRI_TPCs_2018/TPC2/manifesto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manifesto (meta,equipe,resumo,resultados) >
<!ELEMENT meta (id,titulo,subtitulo?,dinicio?,dfim,supervisor) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT dinicio (#PCDATA) >
<!ELEMENT dfim (#PCDATA) >

<!ELEMENT supervisor (nome,email,website) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT website (#PCDATA) >

<!ELEMENT equipe (elemento+) >
<!ELEMENT elemento (id,nome,email, foto) >
<!ELEMENT foto (#PCDATA) >

<!ELEMENT resumo (para+) >
<!ELEMENT para (#PCDATA|b|i)* >
<!ELEMENT b (#PCDATA|i)* >
<!ELEMENT i (#PCDATA|b)* >

<!ELEMENT resultados (resultado+) >
<!ELEMENT resultado (titulo, path) >

<!ELEMENT path (#PCDATA) >

=== cesario74/PRI_TPCs_2018/TPC3/manifesto_tp3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/cp74/Documents/Universidade/PLC/PRI/Tp2/manifesto.dtd">
<manifesto>
    <meta>
        <id>PRI2018::A73883::TP3</id>
        <titulo>Elaboração de Website sobre o Quran</titulo>
        <subtitulo>Relatório inserido nos trabalhos práticos da cadeira de PRI do MIEI
            2018/19</subtitulo>
        <dinicio>06/10/2018</dinicio>
        <dfim>08/10/2018</dfim>
        <supervisor>
            <nome> José Carlos Ramalho </nome>
            <email>jcr@di.uminho.pt</email>
            <website>http://www4.di.uminho.pt/~jcr/</website>
        </supervisor>
    </meta>
    <equipe>
        <elemento>
            <id>73883</id>
            <nome>Cesário Miguel Pereira Perneta</nome>
            <email>a73883@alunos.uminho.pt</email>
            <foto>eu.jpeg</foto>
        </elemento>
    </equipe>
    <resumo>
        <para>
            Neste trabalho foi pedida a criação de um <i>Website</i> do <b>Quran</b>, sobre o qual foi dado um ficheiro <b>XML</b> que continha o respetivo livro.
        </para>
        <para>
            Deste modo, a elaboração do <i>Website</i> foi dividida em duas partes:
        </para> 
        <para>
            - Geração do índice;
        </para>
        <para>
            - Geração das páginas individuais, as quais podem ser acedidas através do índice. 
        </para>
    </resumo>
    <resultados>
        <resultado>
            <titulo>HTML para o quran</titulo>
            <path>Quran/index.html</path>
        </resultado>
        <resultado>
            <titulo>XSL para o quran</titulo>
            <path>quran.xsl</path>
        </resultado>
        <resultado>
            <titulo>XSL para o manifesto</titulo>
            <path>manifesto.xsl</path>
        </resultado>
        <resultado>
            <titulo>XML do manifesto</titulo>
            <path>manifesto_tp3.xml</path>
        </resultado>
        <resultado>
            <titulo>HTML do manifesto</titulo>
            <path>manifesto_tp3.html</path>
        </resultado>
    </resultados>
</manifesto>

=== cesario74/PRI_TPCs_2018/TPC6/Manifesto/manifesto_tp6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/cp74/Documents/Universidade/PLC/PRI/Tp2/manifesto.dtd">
<manifesto>
    <meta>
        <id>PRI2018::A73883::TP6</id>
        <titulo>Website para Registo de Teses - Mestrado e Doutoramento</titulo>
        <subtitulo>Relatório inserido nos trabalhos práticos da cadeira de PRI do MIEI
            2018/19</subtitulo>
        <dinicio>22/10/2018</dinicio>
        <dfim>28/10/2018</dfim>
        <supervisor>
            <nome> José Carlos Ramalho </nome>
            <email>jcr@di.uminho.pt</email>
            <website>http://www4.di.uminho.pt/~jcr/</website>
        </supervisor>
    </meta>
    <equipe>
        <elemento>
            <id>73883</id>
            <nome>Cesário Miguel Pereira Perneta</nome>
            <email>a73883@alunos.uminho.pt</email>
            <foto>eu.jpeg</foto>
        </elemento>
    </equipe>
    <resumo>
        <para>
            Neste trabalho foi pedido que fosse criado um Website para o registo de teses de mestrado e doutoramento.
        </para>
    </resumo>
    <resultados>
        <resultado>
            <titulo>Link para o GitHub com os TPCs de PRI</titulo>
            <path>https://github.com/cesario74/PRI_TPCs_2018/tree/master/TPC6</path>
        </resultado>
    </resultados>
</manifesto>

=== cesario74/PRI_TPCs_2018/TPC4/manifesto_tp4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/cp74/Documents/Universidade/PLC/PRI/Tp2/manifesto.dtd">
<manifesto>
    <meta>
        <id>PRI2018::A73883::TP4</id>
        <titulo>Criação de um Servidor para Website</titulo>
        <subtitulo>Relatório inserido nos trabalhos práticos da cadeira de PRI do MIEI
            2018/19</subtitulo>
        <dinicio>15/10/2018</dinicio>
        <dfim>15/10/2018</dfim>
        <supervisor>
            <nome> José Carlos Ramalho </nome>
            <email>jcr@di.uminho.pt</email>
            <website>http://www4.di.uminho.pt/~jcr/</website>
        </supervisor>
    </meta>
    <equipe>
        <elemento>
            <id>73883</id>
            <nome>Cesário Miguel Pereira Perneta</nome>
            <email>a73883@alunos.uminho.pt</email>
            <foto>eu.jpeg</foto>
        </elemento>
    </equipe>
    <resumo>
        <para>
            Como trabalho de casa, foi pedido que se criasse um <i>Servidor</i> para o <i>Website</i> elaborado na aula. 
            Foi necessário modificar a <i>Stylesheet</i>, para que fossem executadas <b>querys</b> ao servidor e este conseguisse responder.
        </para>
    </resumo>
    <resultados>
        <resultado>
            <titulo>Link para o GitHub com os TPCs de PRI</titulo>
            <path>https://github.com/cesario74/PRI_TPCs_2018</path>
        </resultado>
    </resultados>
</manifesto>

=== cesario74/PRI_TPCs_2018/TPC2/manifesto_tp2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/cp74/Documents/Universidade/PLC/PRI/Tp2/manifesto.dtd">
<manifesto>
    <meta>
        <id>PRI2018::A73883::TP2</id>
        <titulo>Especificação de um DTD para um Processo de Negócio</titulo>
        <subtitulo>Relatório inserido nos trabalhos práticos da cadeira de PRI do MIEI
            2018/19</subtitulo>
        <dinicio>26/09/2018</dinicio>
        <dfim>30/09/2018</dfim>
        <supervisor>
            <nome> José Carlos Ramalho </nome>
            <email>jcr@di.uminho.pt</email>
            <website>http://www4.di.uminho.pt/~jcr/</website>
        </supervisor>
    </meta>
    <equipe>
        <elemento>
            <id>73883</id>
            <nome>Cesário Miguel Pereira Perneta</nome>
            <email>a73883@alunos.uminho.pt</email>
            <foto>eu.jpeg</foto>
        </elemento>
    </equipe>
    <resumo>
        <para>
            Este trabalho prático teve como objetivo aprofundar os conhecimentos adquiridos nas aulas práticas da UC de PRI, acerca de dtd, xsl, xml e html.
        </para>
    </resumo>
    <resultados>
        <resultado>
            <titulo>DTD para o processo de negócio</titulo>
            <path>pn.dtd</path>
        </resultado>
        <resultado>
            <titulo>DTD para o manifesto</titulo>
            <path>manifesto.dtd</path>
        </resultado>
        <resultado>
            <titulo>XSL para o manifesto</titulo>
            <path>manifesto.xsl</path>
        </resultado>
        <resultado>
            <titulo>XML do manifesto</titulo>
            <path>manifesto_tp2.xml</path>
        </resultado>
        <resultado>
            <titulo>HTML do manifesto</titulo>
            <path>manifesto_tp2.html</path>
        </resultado>
    </resultados>
</manifesto>
